from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4
from datetime import datetime

def generate_legal_notice(data, file_path="notice.pdf"):
    doc = SimpleDocTemplate(file_path, pagesize=A4)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        name="TitleCenter",
        parent=styles["Title"],
        alignment=TA_CENTER
    )

    right_style = ParagraphStyle(
        name="RightAlign",
        parent=styles["Normal"],
        alignment=TA_RIGHT
    )

    content = []

    # Title
    content.append(Paragraph("<b>LEGAL NOTICE</b>", title_style))
    content.append(Spacer(1, 12))

    # Date
    content.append(Paragraph(f"Date: {datetime.now().strftime('%d %B %Y')}", right_style))
    content.append(Spacer(1, 12))

    # From / To
    content.append(Paragraph(f"<b>From:</b><br/>{data['sender']}", styles["Normal"]))
    content.append(Spacer(1, 12))

    content.append(Paragraph(f"<b>To:</b><br/>{data['receiver']}", styles["Normal"]))
    content.append(Spacer(1, 12))

    # Subject
    content.append(Paragraph(f"<b>Subject:</b> {data['subject']}", styles["Normal"]))
    content.append(Spacer(1, 12))

    # Body
    body = f"""
    Under instructions from my client, I hereby issue this legal notice:

    1. That the matter concerns: {data['issue']}.
    2. That you have failed to take appropriate action.
    3. That such conduct is unlawful.

    You are hereby called upon to {data['demand']} within {data['timeline']} days
    from receipt of this notice, failing which appropriate legal proceedings
    shall be initiated at your risk.

    This notice is issued without prejudice to all legal rights.
    """

    content.append(Paragraph(body, styles["Normal"]))
    content.append(Spacer(1, 12))

    # Disclaimer
    disclaimer = """
    <b>Disclaimer:</b> This document is generated by an AI system and is intended
    for informational purposes only. It does not constitute legal advice or create
    any attorney-client relationship. Please consult a qualified legal practitioner.
    """

    content.append(Paragraph(disclaimer, styles["Normal"]))
    content.append(Spacer(1, 24))

    # Signature
    content.append(Paragraph("Sincerely,", styles["Normal"]))
    content.append(Spacer(1, 24))
    content.append(Paragraph("__________________________", styles["Normal"]))
    content.append(Paragraph(data['sender'], styles["Normal"]))

    doc.build(content)

    return file_path